phrase:
  access_token: fa67d8a554cacec6a825536b5dc58bcf6d592e3b6bf10cf25468471d3cf62213
  project_id: 0f7cf1c90812914f9b87fb3d513daa20
  push:
    sources:
    - file: ./locales/en-US.json
      params:
        file_format: simple_json
        locale_id: 51ace19f6c3328d26140ff259bf92fd6
  pull:
    targets:
    - file: ./locales/de-DE.json
      params:
        file_format: simple_json
        locale_id: 41ffe7f6454d6f41e3e5ab9a945654c4
